# Generated by Django 4.1.1 on 2022-11-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('to do', 'To do'), ('doing', 'Doing'), ('done', 'Done')], max_length=5),
        ),
    ]
